name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/